# Generated by Django 4.2.29 on 2026-03-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeadlineSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_deadline_time', models.TimeField(verbose_name='order deadline time')),
                ('applies_from', models.DateField(verbose_name='applies from')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'order deadline setting',
                'verbose_name_plural': 'order deadline settings',
                'ordering': ['-applies_from', '-id'],
            },
        ),
    ]
